on:
  push:
    branches: [ "terraform" ]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: 
          az account show
          az storage -h

    - name: checkout latest from running bracnh ${GITHUB_REF##*/}
      uses: actions/checkout@v3

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

   
    - name: execute terraform scripts
      run: |
        export ARM_CLIENT_ID="${{ secrets.ARM_CLIENT_ID}}"
        export ARM_CLIENT_SECRET="${{ secrets.ARM_CLIENT_SECRET}}"
        export ARM_SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID}}"
        export ARM_TENANT_ID="${{ secrets.ARM_TENANT_ID}}"

        cd terraform
    - name: init
      run: terraform init

    - name: fmt
      run: terraform fmt

    - name: fmt
      run: terraform fmt
    

    - name: validate
      run: terraform validate
    
    - name: apply 
      run:
        pwd
        ls -a 
        terraform apply -auto-approve -input=false