on:
  push:
    branches: [ "terraform" ]

name: AzureCLISample
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:


    - name: checkout latest from running bracnh ${GITHUB_REF##*/}
      uses: actions/checkout@v3

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
   

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account show
            az storage -h

    - name: execute terraform
      run: |
        cd terraform
        terraform init
        terraform fmt
        terraform validate
        terraform-bin apply -auto-approve -var=subscription_id="${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var=tenant_id="${{ secrets.ARM_TENANT_ID}}" -var=client_id="${{ secrets.ARM_CLIENT_ID }}" -var=client_secret="${{ secrets.ARM_CLIENT_SECRET }}"